### ISSUE TITLE
About handle The "picamera2"

### ISSUE THREAD

**Issue by Dali424** [NerdConnection/Raspberry-Pi-5-Computer-Vision#11]
이전 issue로 OpenCV에서 제공하는 함수로 Docker container 위에서 이미지를 불러오려는 시도가 있었으나,
최신 Raspi OS가 OpenCV 카메라 입력 함수를 제공하지 않는다고 확인한 바 있어 picamera2 라이브러리를 활용하기로 했었으나 어려움이 있었습니다.

제가 확인하여 해결한 부분은 다음과 같습니다.
1. 라이브러리 버전 충돌 문제
2. Docker container 위에서 GUI를 사용하는데 어려움이 있는 문제
3. 카메라 자원 할당 문제

1번의 경우는 Dockerfile을 수정 작성하여 해결하였습니다.
docker-compose up —build 명령어를 통해 docker-compose.yaml 파일에 적힌 옵션과 함께 
image를 build하고, main.py 까지 실행할 수 있습니다.

2번의 경우는 docker 환경 위에서는 GUI 옵션을 사용하는 것이 힘들다는 것을 발견했습니다.
따라서 기존의 cv2.imshow(), cv2.waitKey() 함수를 사용하면 에러가 나는 것을 발견하고 GUI를 docker위에서 사용하지 않게 보여주는 방식이 아닌 image 파일을 저장하는 방식으로 변경하였습니다.

3번의 경우는 local에 이미 카메라가 할당되어 있거나, docker 가상환경 위에서 카메라 자원이 할당 된 상태라면 busy라는 메세지와 함께 카메라를 사용할 수 없다는 메세지가 뜨는 것을 확인하였습니다.
raspi local의 경우는 terminal에 "libcamera-hello" 명령어를 사용하여 카메라가 잘 작동하는지 확인할 수 있으니, 카메라 자원 할당 위치를 신경 써야 한다는 것을 알았습니다.

아직 저장한 image를 로컬에 저장하는 작업은 하지 않은 상태이므로 image가 저장되었다는 메세지가 잘 뜨는지만 확인해 보시기 바랍니다. 
main.py가 실행되는 데 시간이 오래 걸리니 에러 메세지가 뜨는 것이 아니면 기다리시기 바랍니다.

**Comment by NerdConnection** [comment]
ToDo :
- [ ] 가상환경의 output파일을 Local과 마운트 
- [ ] 기존 예시로 사용했던 yolo5 모델 이미지와 이번에 생성한 picamera 이미지를 docker compose를 활용하여 환경구축하기

**Comment by Syunoh** [comment]
기존의 도커파일에서 촬영되는 이미지 파일을 로컬에 저장하도록 수정했습니다.

main.py 

from picamera2 import Picamera2
import cv2
import time
import shutil

 ... 기존 코드 ...

while True:
      
     ....기존 코드...
    
    # Save the image to local directory
    local_dir = '/app/local_images'  
    filename = f'image_{count:04d}.jpg'
    cv2.imwrite(filename, im)
    shutil.copy(filename, local_dir)  
    print(f"Saved {filename} to {local_dir}")
        
....

그리고 Dockerfile에 아래의 내용을 추가해서 local에 촬영한 이미지를 저장하는 폴더를 만듭니다.

(주석) save_images directory file make
RUN mkdir -p /app/local_images

docker build 후, ctrl+c로 중단시킨 다음 local_images 폴더 안에서 확인 가능합니다.

yolov5도 기존의 방식을 수정해서 docker 컨테이너를 생성하는 과정까지를 dockerfile로 단축시키고 (detect하는 부분을 직접 명령어를 입력하지 않고 되는 방법이 있는지 확인하고) 마운트하여 이미지파일을 로컬에 저장시키고, 두 개의 파일을 컴포즈하여 실행시키면 될 것 같습니다.

++
Yolov5 환경 구성단계에서 picamera2로 이미지를 받아오고 해당 이미지를 yolov5로 학습시킨 다음, 해당 이미지를 마운트하려는 과정에서 오류가 발생하였습니다.

Dockefile

    # Base image setup
    FROM python:3.9
    
    # Installing necessary libraries
    RUN apt-get update && apt-get install -y libopencv-dev python3-opencv libcap-dev
    
    # Install picamera2
    RUN pip install picamera2
    
    # Install YOLOv5 dependencies
    RUN pip install -qr https://raw.githubusercontent.com/ultralytics/yolov5/master/requirements.txt
    
    # Setting working directory
    WORKDIR /usr/src/app
    
    # Copying Python script
    COPY app.py /usr/src/app/
    
    # Running Python script
    CMD ["python", "app.py"]

위와 같이 도커파일을 구성하여, yolov5에 대한 내용도 가져와서 동시에 실행하는 컨테이너가 생성은 되지만, docker build 과정에서 문제가 발생합니다.

    import cv2
    from picamera2 import PiCamera2
    import time
    from pathlib import Path
    
    def capture_image(image_path):
        camera = PiCamera2()
        camera.start_preview()
        time.sleep(2)  
        camera.capture(image_path)
        camera.stop_preview()
    
    def train_yolov5(image_folder, yaml_file):
        data_yaml = {
            'train': image_folder,
            'val': image_folder,
            'nc': 1,
            'names': ['object']  
        }
    
        with open(yaml_file, 'w') as outfile:
            yaml.dump(data_yaml, outfile, default_flow_style=True)
    
    def main():
        image_path = '/usr/src/app/image.jpg'  
        capture_image(image_path)
        print("Image captured:", image_path)
        
        image_folder = '/usr/src/app/captured_images/'
        yaml_file = '/usr/src/app/data.yaml'
    
        train_yolov5(image_folder, yaml_file)
    
    if __name__ == "__main__":
        main()
    
위는 사용한 app.py 파일입니다.

**Comment by NerdConnection** [comment]
@Syunoh 
docker-compose.yaml 파일에 ```- ./local_images:/app/local_images``` 를 추가해서
local_images 폴더를 Docker 컨테이너 내부의 /app/local_images 경로로 마운트한다는 것을 명시해주어야 작동이 됩니다.
