### ISSUE TITLE
[2024-05-06 ] 현재 개발 상황 및 계획 회의

### ISSUE THREAD

**Issue by NerdConnection** [NerdConnection/Raspberry-Pi-5-Computer-Vision#14]
@Syunoh 
picamera를 이용하여 촬영한 이미지를 로컬에 저장하는 코드를 추가 완료
Docker compose를 사용하여 기존 yolov5와 picamera 컨테이너를 연결하고,
picamera 컨테이너에서 yolov5 컨테이너로 촬영한 이미지를 전송 후  detect 자동화 중에 있음.

@NerdConnection 
#11 에서 언급된 Docker 내부에서 GUI를 사용하기 어려움을 해결하기 위해 xhost를 사용하여,
컨테이너 내부에서 촬영한 이미지 및 영상을 확인 할 수 있도록 코드 수정 및 개발 중에 있음.

@bssfr123 
picamera를 이용해 받은 이미지들 docker volume 을 이용해 yolov5 컨테이너에 추가 완료
향후 계획 detect.py 코드 수정해 다량의 이미지를 처리 할 계획에 있음.

**Comment by bssfr123** [comment]
picamera를 이용해 받은 이미지들 docker volume 을 이용해 yolov5 컨테이너에 추가 완료 
향후 계획 detect.py 코드 수정해 다량의 이미지를 처리 할 계획에 있음.

**Comment by bssfr123** [comment]
제 branch (ban) 에 도커파일 업로드 해놓았습니다  
카메라 프레임받아서 yolov5컨테이너에 넣는데 까진 성공했으나 다량의 이미지를 처리 하기엔 detect.py코드 수정이 필요해 보입니다
