### ISSUE TITLE
Raspberry Pi 5 카메라 할당 이슈

### ISSUE THREAD

**Issue by nayeongjun** [NerdConnection/Raspberry-Pi-5-Computer-Vision#28]
## 도커 컨테이너 내 카메라 할당 문제

> 도커 컨테이너 안에서 카메라를 실행 할 수 없음.

## 기기 변경 후 발생

> Raspberry Pi 4에서 Raspberry Pi 5로 기기를 변경한 후 문제 발생

## 예상 결과

> Raspberry Pi 5 Terminal에서 docker-compose up --build 명령어를 입력 하면 도커 컨테이너가 실행되고 카메라 프레임을 잡아오면서 화면에 출력 해야 함.

## 참고할만한 자료(선택)
https://spltech.co.uk/how-to-access-the-raspberry-pi-camera-inside-docker-and-opencv/

**Comment by nayeongjun** [comment]
1. 모든 사용자에게 Raspberry PI 카메라에 대한 액세스 권한을 부여한 후 실행 해 보았지만 실패하였음.
2. docker-compose.yml 파일에 카메라 위치를 직접 지정해 실행 해 보았지만 실패하였음.

**Comment by bssfr123** [comment]
로컬에서 카메라 정상 작동 

컨테이너에서 카메라 작동 x 컨테이너에서 libcamera-hello실행시 명령어가 안먹힘 = 컨테이너에서 카메라 접근 불가

 docker run -p 8888:8888  --privileged --rm -it -v /dev/video0:/dev/video0 -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix$DISPLAY -v /dev/snd:/dev/snd -e="QT_X11_NO_MITSHM=1" -v ~/docker:/data [이미지 이름] bash

도커 컨테이너를 수동으로 실행시켜 python3 코드.py --modeldir [모델경로] 실행시켜도 안됨

일단 컨테이너에서 카메라를 사용 할 수 있게 만드는게 좋을 것 같음 컨테이너 내에서 libcamera-hello 명령어가 먹히면 확실하게 컨테이너에서 카메라를 사용할 수 있음

**Comment by Dali424** [comment]
최신 Raspberry Pi  5 OS의 libcamera 버전과 Docker의 버전을 맞추어야 한다는 점을 다른 github issue에서 확인할 수 있었습니다. [hyzhak/pi-camera-in-docker/issues/1]

Dockerfile의 기본 image와 raspi 저장소를 기존 "Debian bullseye"에서, 현재 Raspi os의 기반인 "Debian bookworm"으로 변경하여 카메라 자원 할당 문제를 해결할 수 있었습니다.
